trigger:
  branches:
    include:
      - dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'crm-frontend'
  registry: 'registry.nafabarter.com'
  fullImageName: '$(registry)/$(imageName)'
  tag: '$(Build.BuildId)'

steps:

- task: Docker@2
  displayName: 'Build and push $(imageName)'
  inputs:
    command: buildAndPush
    containerRegistry: 'nafa-registry'
    repository: '$(imageName)'
    Dockerfile: 'Dockerfile'
    tags: |
      latest
      $(tag)
    
- task: SSH@0
  displayName: 'Deploy CRM Frontend'
  inputs:
    sshEndpoint: 'hostinger-vps'
    runOptions: inline
    inline: |
      set -e

      IMAGE_TAG=$(Build.BuildId)
      IMAGE=registry.nafabarter.com/crm-frontend:$IMAGE_TAG

      echo "Deploying $IMAGE"

      # Stop and remove old container
      docker rm -f crm-frontend || true

      # Pull latest image
      docker pull $IMAGE

      # Run container
      docker run -d \
        --name crm-frontend \
        -p 5173:80 \
        --restart always \
        $IMAGE