import hrApi from "./hr.api";

export const getAllPayroll = () => hrApi.get("/api/Payroll/all");
export const getPayrollByEmployee = (userId) => hrApi.get(`/api/Payroll/${userId}`);
export const generatePayroll = (data) => hrApi.post("/api/Payroll/generate", data);
export const updatePayroll = (id, data) => hrApi.put(`/api/Payroll/${id}`, data);
export const deletePayroll = (id) => hrApi.delete(`/api/Payroll/${id}`);
export const approvePayroll = (id) => hrApi.put(`/api/Payroll/${id}/approve`);
export const markPaid = (id) => hrApi.put(`/api/Payroll/${id}/mark-paid`);
export const addAllowance = (data) => hrApi.post("/api/Payroll/allowance", data);
export const addDeduction = (data) => hrApi.post("/api/Payroll/deduction", data);
export const getPayslip = (userId) => hrApi.get(`/api/Payroll/payslip/current/${userId}`);
export const setSalaryConfig = (data) => hrApi.post("/api/Payroll/salary-config", data);
export const getSalaryConfig = (userId) => hrApi.get(`/api/Payroll/salary-config/${userId}`);
export const getAllSalaryConfig = () => hrApi.get("/api/Payroll/salary-config/all");
export const autoGeneratePayroll = () => hrApi.post("/api/Payroll/auto-generate");
export const addBonus = (data) => hrApi.post("/api/Payroll/bonus", data);
export const approveBonus = (id) => hrApi.put(`/api/Payroll/bonus/${id}/approve`);
export const getAllBonuses = () => hrApi.get("/api/Payroll/bonus/all");
export const getBonusByUser = (userId) => hrApi.get(`/api/Payroll/bonus/${userId}`);
